---
abstract: ~
author:
  - 'Rob Kinyon <rob.kinyon@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  HTTP::Request: '0.01'
  LWP::UserAgent: '0.01'
  Test::DBIx::Class: '0.01'
  Test::Deep: '0.01'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Class::Sims::REST
name: DBIx-Class-Sims-REST
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBIx::Class::Sims: 0
  Hash::Merge: 0
  JSON::XS: 0
  Plack::Request: 0
  Web::Simple: 0
  perl: 5.8.0
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class-Sims-REST
  homepage: http://search.cpan.org/perldoc?DBIx%3A%3AClass%3A%3ASims%3A%3AREST
  license: http://dev.perl.org/licenses/
  repository: https://github.com/robkinyon/dbix-class-sims-rest
version: '0.000011'
